name:                magic-tyfams
version:             0.1.0.0
github:              "https://github.com/isovector/type-sets/tree/master/cmptype"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Write plugins for magic type families with ease
category:            Compiler Plugin

description:         Please see the README on GitHub at <https://github.com/isovector/type-sets/tree/master/cmptype#readme>

dependencies:
- base >= 4.7 && < 5
- ghc
- ghc-tcplugins-extra
- syb

library:
  source-dirs: src

